### ISSUE TITLE
Moving away from the 'New' tab deletes your work.

### ISSUE THREAD

**Issue by mitchell-es** [esnet/oscars-frontend#68] opened 2018-02-12 16:56 UTC
If you move to the 'List' or 'Details' tab from the 'New' tab and come back, your work is gone. The site should either save your work or give you a warning before letting you move to another tab.

**Comment by haniotak** [comment] 2018-02-12 17:30
closing as a duplicate of #33; also you'll be happy to know the in-progress dev build fixes this. :)

**Closed by haniotak** 2018-02-12 17:30 UTC
